### ISSUE TITLE
program not working even though i enabled 260 character limit (im using a laptop)

### ISSUE THREAD

**Issue by Mossza324** [tuokri/rs2-audio-extractor#2]
Traceback (most recent call last):
  File "concurrent\futures\process.py", line 243, in _process_worker
  File "extract.py", line 189, in decode_bank
  File "subprocess.py", line 420, in check_output
  File "subprocess.py", line 501, in run
  File "subprocess.py", line 966, in __init__
  File "subprocess.py", line 1435, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "concurrent\futures\process.py", line 243, in _process_worker
  File "extract.py", line 175, in decode_banks
  File "concurrent\futures\_base.py", line 438, in result
  File "concurrent\futures\_base.py", line 390, in __get_result
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "extract.py", line 514, in <module>
  File "extract.py", line 388, in main
  File "concurrent\futures\_base.py", line 438, in result
  File "concurrent\futures\_base.py", line 390, in __get_result
FileNotFoundError: [WinError 2] The system cannot find the file specified
[17596] Failed to execute script 'extract' due to unhandled exception!
Exception in thread Thread-1 (_target):
Traceback (most recent call last):
  File "multiprocessing\connection.py", line 317, in _recv_bytes
Traceback (most recent call last):
BrokenPipeError: [WinError 109] The pipe has been ended
  File "multiprocessing\connection.py", line 317, in _recv_bytes

During handling of the above exception, another exception occurred:

BrokenPipeError: [WinError 109] The pipe has been ended
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

  File "threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "threading.py", line 946, in run
  File "extract.py", line 306, in id_to_filename_worker
  File "logbook\queues.py", line 276, in _target
  File "<string>", line 2, in get
  File "logbook\queues.py", line 298, in dispatch_once
  File "multiprocessing\managers.py", line 818, in _callmethod
  File "logbook\queues.py", line 565, in recv
  File "multiprocessing\connection.py", line 255, in recv
  File "<string>", line 2, in get
  File "multiprocessing\connection.py", line 326, in _recv_bytes
  File "multiprocessing\managers.py", line 818, in _callmethod
EOFError
  File "multiprocessing\connection.py", line 255, in recv

During handling of the above exception, another exception occurred:

  File "multiprocessing\connection.py", line 326, in _recv_bytes
Traceback (most recent call last):
EOFError
  File "logbook\handlers.py", line 216, in handle
  File "logbook\queues.py", line 511, in emit
  File "<string>", line 2, in put_nowait
  File "multiprocessing\managers.py", line 817, in _callmethod
  File "multiprocessing\connection.py", line 211, in send
  File "multiprocessing\connection.py", line 285, in _send_bytes
BrokenPipeError: [WinError 232] The pipe is being closed
Logged from file C:\Users\User\extract.py, line 315

**Comment by Mossza324** [comment]
sorry i forgot to install python

**Comment by Mossza324** [comment]
nevermind what i said, it's not working now
